on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
      - run: |
            ssh -o StrictHostKeyChecking=no ubuntu@${{ vars.VPS_HOST }} << 'EOF'
              cd ~/PA_CopainQuartier
              git pull
              docker-compose down
              docker-compose up -d --build
            EOF